version: "3.1"

services:
  api:
    build:
      context: .
      dockerfile: Application.Dockerfile
    command: /usr/local/bin/http
    environment:
      BASE_URL: https://s3-eu-west-1.amazonaws.com/test-golang-recipes/
    ports:
      - 8080:80